<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <!-- General build properties -->
    <PropertyGroup>
        <!-- Current machine operating system -->
        <_OSArchitecture>$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)</_OSArchitecture>
        <_IsWindows>$([System.OperatingSystem]::IsWindows())</_IsWindows>
        <_IsLinux>$([System.OperatingSystem]::IsLinux())</_IsLinux>
        <_IsMacOS>$([System.OperatingSystem]::IsMacOS())</_IsMacOS>
        
        <!-- Current project build configuration -->
        <_IsRelease>$([System.String]::Equals($(Configuration), 'Release'))</_IsRelease>
        <_IsDebug>$([System.String]::Equals($(Configuration), 'Debug'))</_IsDebug>
         
        <!-- Current RID build configuration -->
        <_IsWindowsTarget>false</_IsWindowsTarget>
        <_IsWindowsTarget Condition="'$(RuntimeIdentifier)' == 'win-x64' Or '$(RuntimeIdentifier)' == 'win-arm64'">true</_IsWindowsTarget>

        <_IsLinuxTarget>false</_IsLinuxTarget>
        <_IsLinuxTarget Condition="'$(RuntimeIdentifier)' == 'linux-x64' Or '$(RuntimeIdentifier)' == 'linux-arm64'">true</_IsLinuxTarget>

        <_IsMacOSTarget>false</_IsMacOSTarget>
        <_IsMacOSTarget Condition="'$(RuntimeIdentifier)' == 'osx-x64' Or '$(RuntimeIdentifier)' == 'osx-arm64'">true</_IsMacOSTarget>
        
        <!-- Current build environment -->
        <_IsCI>false</_IsCI>
        <_IsCI Condition="'$(GITHUB_ACTIONS)' == 'true' Or '$(CI)' == 'true'">true</_IsCI>
    </PropertyGroup>

    <!-- Git info properties -->
    <PropertyGroup>
        <_GitRootPath>$(MSBuildThisFileDirectory)\.git\</_GitRootPath>
        <_GitRefFilePath>$(_GitRootPath)HEAD</_GitRefFilePath>
        <_GitRefHashFilePath Condition="Exists('$(_GitRefFilePath)')">$([System.IO.File]::ReadAllText('$(_GitRefFilePath)').Trim().Substring(5))</_GitRefHashFilePath>
        <_GitRefHashFilePath Condition="!$([System.Text.RegularExpressions.Regex]::IsMatch('$(_GitRefHashFilePath)', '^[0-9a-fA-F]+$'))">$(_GitRootPath)$(_GitRefHashFilePath)</_GitRefHashFilePath>
        <!-- If detached head, hash is in .git/HEAD file. -->
        <_GitRefHashFilePath Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(_GitRefHashFilePath)', '^[0-9a-fA-F]+$'))">$(_GitRefFilePath)</_GitRefHashFilePath>
        <_GitHash Condition="Exists('$(_GitRefHashFilePath)')">$([System.IO.File]::ReadAllText('$(_GitRefHashFilePath)').Trim())</_GitHash>
    </PropertyGroup>

    <!-- Game properties -->
    <PropertyGroup>
        <GameName Condition="'$(GameName)' == ''">$(NITROX_GAME_NAME)</GameName>
        <GameName Condition="'$(GameName)' == ''">Subnautica</GameName>
        <GameMinimumVersion Condition="'$(GameMinimumVersion)' == ''">$(NITROX_GAME_MINIMUM_VERSION)</GameMinimumVersion>
        <GameMinimumVersion Condition="'$(GameMinimumVersion)' == ''">82304</GameMinimumVersion>
        <!-- Root installation path of the game (usually where the executable is located) -->
        <GameInstallationPath Condition="'$(GameInstallationPath)' == ''">$(SUBNAUTICA_INSTALLATION_PATH)</GameInstallationPath>
        <GameInstallationPath Condition="'$(GameInstallationPath)' == ''">$(NITROX_GAME_INSTALLATION_PATH)</GameInstallationPath>
        <!-- Name of the folder that contains the game data (assets, configs, ...) -->
        <GameDataFolder Condition="'$(GameDataFolder)' == ''">$(NITROX_GAME_DATA_FOLDER)</GameDataFolder>
        <GameDataFolder Condition="'$(GameDataFolder)' == '' and '$(_IsMacOS)' == 'true'">Resources/Data</GameDataFolder>
        <GameDataFolder Condition="'$(GameDataFolder)' == ''">Subnautica_Data</GameDataFolder>
        <!-- Name of the folder that contains the managed game assemblies -->
        <GameManagedFolder Condition="'$(GameManagedFolder)' == ''">$(NITROX_GAME_MANAGED_FOLDER)</GameManagedFolder>
        <GameManagedFolder Condition="'$(GameManagedFolder)' == ''">Managed</GameManagedFolder>
        <!-- Relative path to the game version file -->
        <GameVersionRelativePath Condition="'$(GameVersionRelativePath)' == ''">$(NITROX_GAME_VERSION_RELATIVE_PATH)</GameVersionRelativePath>
        <GameVersionRelativePath Condition="'$(GameVersionRelativePath)' == ''">StreamingAssets/SNUnmanagedData/plastic_status.ignore</GameVersionRelativePath>
    </PropertyGroup>

</Project>
